from machine import SPI

SPI_DUMMY_INT = 0x00
SPI_TRANSFER_LEN = 1
SPI_HOLD_US = 50

SPI_DEFAULT_BAUDRATE = 10000000  # 10MHz
SPI_DEFAULT_FIRSTBIT = SPI.MSB
SPI_DEFAULT_POLARITY = 0
SPI_DEFAULT_PHASE = 0